version: "3.5"

# source /opt/ros/foxy/setup.bash && \
#    colcon build

services:
  # ros2:
  #   image: osrf/ros:foxy-desktop
  #   restart: always
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   container_name: ros2
  #   privileged: true
  #   network_mode: host
  #   volumes:
  #     - ./rpi_ws:/rpi_ws
  #     - ./server:/server_ws
  #     - /dev/shm:/dev/shm
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - /dev/input:/dev/input # For Joystick
  #   environment:
  #     - DISPLAY=:1
  #   #  - ROS_DOMAIN_ID=5

  rosnoetic:
    image: ros:noetic-ros-base-focal
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: rosnoetic
    privileged: true
    network_mode: host
    volumes:
      - ./rpi_ws:/rpi_ws
      - ./server-ros1:/server_ws
    #  - /dev/shm:/dev/shm
    #  - /tmp/.X11-unix:/tmp/.X11-unix
    #  - /dev/input:/dev/input # For Joystick
    environment:
    #  - DISPLAY=:1
      - DISPLAY=192.168.178.120:0.0
      - ROS_MASTER_URI=http://192.168.178.94:11311
      - ROS_IP=192.168.178.120
      - ROS_HOSTNAME=192.168.178.120