set(_AMENT_PACKAGE_NAME "moveit_ros_planning")
set(moveit_ros_planning_VERSION "2.2.3")
set(moveit_ros_planning_MAINTAINER "Michael Ferguson <mferguson@fetchrobotics.com>, Michael Görner <me@v4hn.de>, MoveIt Release Team <moveit_releasers@googlegroups.com>")
set(moveit_ros_planning_BUILD_DEPENDS "moveit_common" "ament_index_cpp" "moveit_core" "moveit_ros_occupancy_map_monitor" "moveit_msgs" "message_filters" "pluginlib" "rclcpp_action" "rclcpp" "srdfdom" "urdf" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_msgs" "tf2_ros" "eigen")
set(moveit_ros_planning_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_planning_BUILDTOOL_DEPENDS "ament_cmake" "eigen3_cmake_module")
set(moveit_ros_planning_BUILD_EXPORT_DEPENDS "ament_index_cpp" "moveit_core" "moveit_ros_occupancy_map_monitor" "moveit_msgs" "message_filters" "pluginlib" "rclcpp_action" "rclcpp" "srdfdom" "urdf" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_msgs" "tf2_ros" "eigen")
set(moveit_ros_planning_BUILD_EXPORT_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_planning_BUILDTOOL_EXPORT_DEPENDS "eigen3_cmake_module")
set(moveit_ros_planning_EXEC_DEPENDS "ament_index_cpp" "moveit_core" "moveit_ros_occupancy_map_monitor" "moveit_msgs" "message_filters" "pluginlib" "rclcpp_action" "rclcpp" "srdfdom" "urdf" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_msgs" "tf2_ros" "eigen")
set(moveit_ros_planning_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_planning_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gmock" "ament_cmake_gtest" "moveit_resources_panda_moveit_config")
set(moveit_ros_planning_GROUP_DEPENDS )
set(moveit_ros_planning_MEMBER_OF_GROUPS )
set(moveit_ros_planning_DEPRECATED "")
set(moveit_ros_planning_EXPORT_TAGS)
list(APPEND moveit_ros_planning_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
