set(_AMENT_PACKAGE_NAME "moveit_core")
set(moveit_core_VERSION "2.2.3")
set(moveit_core_MAINTAINER "Dave Coleman <dave@picknik.ai>, Michael Görner <me@v4hn.de>, Michael Ferguson <mferguson@fetchrobotics.com>, MoveIt Release Team <moveit_releasers@googlegroups.com>")
set(moveit_core_BUILD_DEPENDS "moveit_common" "angles" "rclcpp" "common_interfaces" "assimp" "boost" "eigen" "bullet" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "urdf" "urdfdom" "urdfdom_headers" "moveit_msgs" "octomap" "octomap_msgs" "pluginlib" "pybind11_vendor" "random_numbers" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs")
set(moveit_core_BUILDTOOL_DEPENDS "ament_cmake" "pkg-config" "eigen3_cmake_module")
set(moveit_core_BUILD_EXPORT_DEPENDS "angles" "rclcpp" "common_interfaces" "assimp" "boost" "eigen" "bullet" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "urdf" "urdfdom" "urdfdom_headers" "moveit_msgs" "octomap" "octomap_msgs" "pluginlib" "pybind11_vendor" "random_numbers" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs")
set(moveit_core_BUILDTOOL_EXPORT_DEPENDS "eigen3_cmake_module")
set(moveit_core_EXEC_DEPENDS "angles" "rclcpp" "common_interfaces" "assimp" "boost" "eigen" "bullet" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "urdf" "urdfdom" "urdfdom_headers" "moveit_msgs" "octomap" "octomap_msgs" "pluginlib" "pybind11_vendor" "random_numbers" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs")
set(moveit_core_TEST_DEPENDS "moveit_resources_panda_moveit_config" "moveit_resources_pr2_description" "angles" "tf2_kdl" "orocos_kdl" "ament_cmake_gtest" "ament_index_cpp" "ament_lint_auto" "ament_lint_common")
set(moveit_core_GROUP_DEPENDS )
set(moveit_core_MEMBER_OF_GROUPS )
set(moveit_core_DEPRECATED "")
set(moveit_core_EXPORT_TAGS)
list(APPEND moveit_core_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND moveit_core_EXPORT_TAGS "<moveit_core plugin=\"collision_detector_fcl_description.xml\"/>")
list(APPEND moveit_core_EXPORT_TAGS "<moveit_core plugin=\"collision_detector_bullet_description.xml\"/>")
