set(_AMENT_PACKAGE_NAME "moveit_arduino_arm")
set(moveit_arduino_arm_VERSION "0.3.0")
set(moveit_arduino_arm_MAINTAINER "Christian Peeren <christian.peeren@gmail.com>")
set(moveit_arduino_arm_BUILD_DEPENDS )
set(moveit_arduino_arm_BUILDTOOL_DEPENDS "ament_cmake")
set(moveit_arduino_arm_BUILD_EXPORT_DEPENDS )
set(moveit_arduino_arm_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_arduino_arm_EXEC_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "tf2_ros" "xacro" "arm_model" "controller_manager" "moveit_configs_utils" "moveit_ros_move_group" "moveit_ros_visualization" "moveit_ros_warehouse" "moveit_setup_assistant" "robot_state_publisher" "rviz2" "rviz_common" "rviz_default_plugins" "tf2_ros" "warehouse_ros_mongo")
set(moveit_arduino_arm_TEST_DEPENDS )
set(moveit_arduino_arm_GROUP_DEPENDS )
set(moveit_arduino_arm_MEMBER_OF_GROUPS )
set(moveit_arduino_arm_DEPRECATED "")
set(moveit_arduino_arm_EXPORT_TAGS)
list(APPEND moveit_arduino_arm_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
