set(_AMENT_PACKAGE_NAME "moveit_ros_occupancy_map_monitor")
set(moveit_ros_occupancy_map_monitor_VERSION "2.2.3")
set(moveit_ros_occupancy_map_monitor_MAINTAINER "Michael Ferguson <mferguson@fetchrobotics.com>, MoveIt Release Team <moveit_releasers@googlegroups.com>")
set(moveit_ros_occupancy_map_monitor_BUILD_DEPENDS "moveit_common" "eigen" "rclcpp" "moveit_core" "moveit_msgs" "octomap" "pluginlib" "tf2_ros" "geometric_shapes")
set(moveit_ros_occupancy_map_monitor_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_occupancy_map_monitor_BUILDTOOL_DEPENDS "ament_cmake" "eigen3_cmake_module")
set(moveit_ros_occupancy_map_monitor_BUILD_EXPORT_DEPENDS "eigen" "rclcpp" "moveit_core" "moveit_msgs" "octomap" "pluginlib" "tf2_ros" "geometric_shapes")
set(moveit_ros_occupancy_map_monitor_BUILD_EXPORT_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_occupancy_map_monitor_BUILDTOOL_EXPORT_DEPENDS "eigen3_cmake_module")
set(moveit_ros_occupancy_map_monitor_EXEC_DEPENDS "rclcpp" "moveit_core" "moveit_msgs" "octomap" "pluginlib" "tf2_ros" "geometric_shapes")
set(moveit_ros_occupancy_map_monitor_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(moveit_ros_occupancy_map_monitor_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(moveit_ros_occupancy_map_monitor_GROUP_DEPENDS )
set(moveit_ros_occupancy_map_monitor_MEMBER_OF_GROUPS )
set(moveit_ros_occupancy_map_monitor_DEPRECATED "")
set(moveit_ros_occupancy_map_monitor_EXPORT_TAGS)
list(APPEND moveit_ros_occupancy_map_monitor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
