# CMake generated Testfile for 
# Source directory: /server_ws/src/moveit2/moveit_core/robot_state
# Build directory: /server_ws/build/moveit_core/robot_state
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_robot_state "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_robot_state.txt" "--append-env" "LD_LIBRARY_PATH=/server_ws/build/moveit_core/robot_state" "LD_LIBRARY_PATH=/server_ws/build/moveit_core/robot_state/../utils" "--command" "/server_ws/build/moveit_core/robot_state/test_robot_state" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state.gtest.xml")
set_tests_properties(test_robot_state PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/robot_state/test_robot_state" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/robot_state" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;42;ament_add_gtest;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;0;")
add_test(test_robot_state_benchmark "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state_benchmark.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_robot_state_benchmark.txt" "--command" "/server_ws/build/moveit_core/robot_state/test_robot_state_benchmark" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state_benchmark.gtest.xml")
set_tests_properties(test_robot_state_benchmark PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/robot_state/test_robot_state_benchmark" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/robot_state" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;53;ament_add_gtest;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;0;")
add_test(test_robot_state_complex "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state_complex.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_robot_state_complex.txt" "--command" "/server_ws/build/moveit_core/robot_state/test_robot_state_complex" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_robot_state_complex.gtest.xml")
set_tests_properties(test_robot_state_complex PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/robot_state/test_robot_state_complex" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/robot_state" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;61;ament_add_gtest;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;0;")
add_test(test_aabb "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_aabb.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_aabb.txt" "--command" "/server_ws/build/moveit_core/robot_state/test_aabb" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_aabb.gtest.xml")
set_tests_properties(test_aabb PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/robot_state/test_aabb" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/robot_state" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;69;ament_add_gtest;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;0;")
add_test(test_cartesian_interpolator "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_cartesian_interpolator.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_cartesian_interpolator.txt" "--command" "/server_ws/build/moveit_core/robot_state/test_cartesian_interpolator" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_cartesian_interpolator.gtest.xml")
set_tests_properties(test_cartesian_interpolator PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/robot_state/test_cartesian_interpolator" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/robot_state" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;77;ament_add_gtest;/server_ws/src/moveit2/moveit_core/robot_state/CMakeLists.txt;0;")
