# generated from colcon_core/shell/template/command_prefix.sh.em
. "/server_ws/install/moveit_common/share/moveit_common/package.sh"
. "/server_ws/install/moveit_core/share/moveit_core/package.sh"
. "/server_ws/install/moveit_ros_occupancy_map_monitor/share/moveit_ros_occupancy_map_monitor/package.sh"
. "/server_ws/install/moveit_ros_planning/share/moveit_ros_planning/package.sh"
. "/server_ws/install/moveit_kinematics/share/moveit_kinematics/package.sh"
. "/server_ws/install/moveit_ros_robot_interaction/share/moveit_ros_robot_interaction/package.sh"
. "/server_ws/install/moveit_ros_warehouse/share/moveit_ros_warehouse/package.sh"
. "/server_ws/install/moveit_ros_move_group/share/moveit_ros_move_group/package.sh"
. "/server_ws/install/moveit_ros_planning_interface/share/moveit_ros_planning_interface/package.sh"
