# CMake generated Testfile for 
# Source directory: /server_ws/src/moveit2/moveit_kinematics/test
# Build directory: /server_ws/build/moveit_kinematics/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_launch_fanuc-kdl-singular.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl-singular.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/fanuc-kdl-singular.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl-singular.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_fanuc-kdl-singular.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;20;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_fanuc-kdl.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/fanuc-kdl.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_fanuc-kdl.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;21;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_panda-kdl-singular.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl-singular.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/panda-kdl-singular.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl-singular.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_panda-kdl-singular.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;22;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_panda-kdl.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/panda-kdl.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_panda-kdl.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;23;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_fanuc-lma-singular.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-lma-singular.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/fanuc-lma-singular.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-lma-singular.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_fanuc-lma-singular.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;27;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_fanuc-lma.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-lma.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/fanuc-lma.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-lma.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_fanuc-lma.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;28;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_panda-lma-singular.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-lma-singular.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/panda-lma-singular.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-lma-singular.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_panda-lma-singular.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;29;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
add_test(test_launch_panda-lma.test.py "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-lma.test.py.xunit.xml" "--package-name" "moveit_kinematics" "--output-file" "/server_ws/build/moveit_kinematics/ros_test/CHANGEME.txt" "--command" "ros2" "test" "/server_ws/src/moveit2/moveit_kinematics/test/launch/panda-lma.test.py" "test_binary_dir:=/server_ws/build/moveit_kinematics/test" "--junit-xml=/server_ws/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-lma.test.py.xunit.xml" "--package-name=moveit_kinematics")
set_tests_properties(test_launch_panda-lma.test.py PROPERTIES  TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_kinematics/test" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ros_testing/cmake/add_ros_test.cmake;73;ament_add_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;30;add_ros_test;/server_ws/src/moveit2/moveit_kinematics/test/CMakeLists.txt;0;")
subdirs("../gtest")
