set(_AMENT_PACKAGE_NAME "moveit_common")
set(moveit_common_VERSION "2.2.3")
set(moveit_common_MAINTAINER "MoveIt Release Team <moveit_releasers@googlegroups.com>")
set(moveit_common_BUILD_DEPENDS )
set(moveit_common_BUILDTOOL_DEPENDS "ament_cmake")
set(moveit_common_BUILD_EXPORT_DEPENDS )
set(moveit_common_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_common_EXEC_DEPENDS )
set(moveit_common_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(moveit_common_GROUP_DEPENDS )
set(moveit_common_MEMBER_OF_GROUPS )
set(moveit_common_DEPRECATED "")
set(moveit_common_EXPORT_TAGS)
list(APPEND moveit_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
