# Default initial positions for mrm's ros2_control fake system

initial_positions:
  base_link__link_01: 0
  link_01__link_02: 0
  link_02__link_03: 0
  link_03__link_04: 0
  link_05__link_clawL: 0
  link_05__link_clawR: 0