# CMake generated Testfile for 
# Source directory: /server_ws/src/moveit2/moveit_ros/moveit_servo
# Build directory: /server_ws/build/moveit_servo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_low_pass_filter "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_servo/test_results/moveit_servo/test_low_pass_filter.gtest.xml" "--package-name" "moveit_servo" "--output-file" "/server_ws/build/moveit_servo/ament_cmake_gtest/test_low_pass_filter.txt" "--command" "/server_ws/build/moveit_servo/test_low_pass_filter" "--gtest_output=xml:/server_ws/build/moveit_servo/test_results/moveit_servo/test_low_pass_filter.gtest.xml")
set_tests_properties(test_low_pass_filter PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_servo/test_low_pass_filter" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_servo" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;184;ament_add_gtest;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(enforce_limits_tests "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_servo/test_results/moveit_servo/enforce_limits_tests.gtest.xml" "--package-name" "moveit_servo" "--output-file" "/server_ws/build/moveit_servo/ament_cmake_gtest/enforce_limits_tests.txt" "--command" "/server_ws/build/moveit_servo/enforce_limits_tests" "--gtest_output=xml:/server_ws/build/moveit_servo/test_results/moveit_servo/enforce_limits_tests.gtest.xml")
set_tests_properties(enforce_limits_tests PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_servo/enforce_limits_tests" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_servo" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;254;ament_add_gtest;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(lint_cmake "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_servo/test_results/moveit_servo/lint_cmake.xunit.xml" "--package-name" "moveit_servo" "--output-file" "/server_ws/build/moveit_servo/ament_lint_cmake/lint_cmake.txt" "--command" "/opt/ros/foxy/bin/ament_lint_cmake" "--xunit-file" "/server_ws/build/moveit_servo/test_results/moveit_servo/lint_cmake.xunit.xml")
set_tests_properties(lint_cmake PROPERTIES  LABELS "lint_cmake;linter" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/src/moveit2/moveit_ros/moveit_servo" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake;41;ament_add_test;/opt/ros/foxy/share/ament_cmake_lint_cmake/cmake/ament_cmake_lint_cmake_lint_hook.cmake;21;ament_lint_cmake;/opt/ros/foxy/share/ament_cmake_lint_cmake/cmake/ament_cmake_lint_cmake_lint_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;21;ament_execute_extensions;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_package.cmake;66;ament_execute_extensions;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;261;ament_package;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(pep257 "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_servo/test_results/moveit_servo/pep257.xunit.xml" "--package-name" "moveit_servo" "--output-file" "/server_ws/build/moveit_servo/ament_pep257/pep257.txt" "--command" "/opt/ros/foxy/bin/ament_pep257" "--xunit-file" "/server_ws/build/moveit_servo/test_results/moveit_servo/pep257.xunit.xml")
set_tests_properties(pep257 PROPERTIES  LABELS "pep257;linter" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/src/moveit2/moveit_ros/moveit_servo" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_pep257/cmake/ament_pep257.cmake;41;ament_add_test;/opt/ros/foxy/share/ament_cmake_pep257/cmake/ament_cmake_pep257_lint_hook.cmake;18;ament_pep257;/opt/ros/foxy/share/ament_cmake_pep257/cmake/ament_cmake_pep257_lint_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;21;ament_execute_extensions;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_package.cmake;66;ament_execute_extensions;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;261;ament_package;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;0;")
add_test(xmllint "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_servo/test_results/moveit_servo/xmllint.xunit.xml" "--package-name" "moveit_servo" "--output-file" "/server_ws/build/moveit_servo/ament_xmllint/xmllint.txt" "--command" "/opt/ros/foxy/bin/ament_xmllint" "--xunit-file" "/server_ws/build/moveit_servo/test_results/moveit_servo/xmllint.xunit.xml")
set_tests_properties(xmllint PROPERTIES  LABELS "xmllint;linter" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/src/moveit2/moveit_ros/moveit_servo" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_xmllint/cmake/ament_xmllint.cmake;50;ament_add_test;/opt/ros/foxy/share/ament_cmake_xmllint/cmake/ament_cmake_xmllint_lint_hook.cmake;18;ament_xmllint;/opt/ros/foxy/share/ament_cmake_xmllint/cmake/ament_cmake_xmllint_lint_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;21;ament_execute_extensions;/opt/ros/foxy/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake;0;;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake;48;include;/opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_package.cmake;66;ament_execute_extensions;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;261;ament_package;/server_ws/src/moveit2/moveit_ros/moveit_servo/CMakeLists.txt;0;")
subdirs("gtest")
