set(_AMENT_PACKAGE_NAME "moveit")
set(moveit_VERSION "2.2.3")
set(moveit_MAINTAINER "Dave Coleman <dave@picknik.ai>, Michael Ferguson <mferguson@fetchrobotics.com>, Michael Görner <me@v4hn.de>, Robert Haschke <rhaschke@techfak.uni-bielefeld.de>, Ian McMahon <imcmahon01@gmail.com>, Isaac I. Y. Saito <130s@2000.jukuin.keio.ac.jp>")
set(moveit_BUILD_DEPENDS )
set(moveit_BUILDTOOL_DEPENDS "ament_cmake")
set(moveit_BUILD_EXPORT_DEPENDS )
set(moveit_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_EXEC_DEPENDS "moveit_core" "moveit_planners" "moveit_plugins" "moveit_ros")
set(moveit_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(moveit_GROUP_DEPENDS )
set(moveit_MEMBER_OF_GROUPS )
set(moveit_DEPRECATED "")
set(moveit_EXPORT_TAGS)
list(APPEND moveit_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
