set(_AMENT_PACKAGE_NAME "moveit_servo")
set(moveit_servo_VERSION "2.2.3")
set(moveit_servo_MAINTAINER "Blake Anderson <blakeanderson@utexas.edu>, Andy Zelenak <andyz@utexas.edu>")
set(moveit_servo_BUILD_DEPENDS "moveit_common" "control_msgs" "control_toolbox" "geometry_msgs" "moveit_msgs" "moveit_ros_planning_interface" "sensor_msgs" "std_msgs" "std_srvs" "tf2_eigen" "trajectory_msgs")
set(moveit_servo_BUILDTOOL_DEPENDS "ament_cmake")
set(moveit_servo_BUILD_EXPORT_DEPENDS "control_msgs" "control_toolbox" "geometry_msgs" "moveit_msgs" "moveit_ros_planning_interface" "sensor_msgs" "std_msgs" "std_srvs" "tf2_eigen" "trajectory_msgs")
set(moveit_servo_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_servo_EXEC_DEPENDS "gripper_controllers" "joint_state_broadcaster" "joint_trajectory_controller" "joy" "tf2_ros" "robot_state_publisher" "control_msgs" "control_toolbox" "geometry_msgs" "moveit_msgs" "moveit_ros_planning_interface" "sensor_msgs" "std_msgs" "std_srvs" "tf2_eigen" "trajectory_msgs")
set(moveit_servo_TEST_DEPENDS "moveit_resources_panda_moveit_config" "ros_testing" "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(moveit_servo_GROUP_DEPENDS )
set(moveit_servo_MEMBER_OF_GROUPS )
set(moveit_servo_DEPRECATED "")
set(moveit_servo_EXPORT_TAGS)
list(APPEND moveit_servo_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
