# CMake generated Testfile for 
# Source directory: /server_ws/src/moveit2/moveit_core/collision_detection_fcl
# Build directory: /server_ws/build/moveit_core/collision_detection_fcl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_fcl_collision_env "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_env.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_fcl_collision_env.txt" "--command" "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_env" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_env.gtest.xml")
set_tests_properties(test_fcl_collision_env PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_env" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/collision_detection_fcl" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;49;ament_add_gtest;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;0;")
add_test(test_fcl_collision_detection "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_detection.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_fcl_collision_detection.txt" "--command" "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_detection" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_detection.gtest.xml")
set_tests_properties(test_fcl_collision_detection PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_detection" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/collision_detection_fcl" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;52;ament_add_gtest;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;0;")
add_test(test_fcl_collision_detection_panda "/usr/bin/python3" "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_detection_panda.gtest.xml" "--package-name" "moveit_core" "--output-file" "/server_ws/build/moveit_core/ament_cmake_gtest/test_fcl_collision_detection_panda.txt" "--command" "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_detection_panda" "--gtest_output=xml:/server_ws/build/moveit_core/test_results/moveit_core/test_fcl_collision_detection_panda.gtest.xml")
set_tests_properties(test_fcl_collision_detection_panda PROPERTIES  LABELS "gtest" REQUIRED_FILES "/server_ws/build/moveit_core/collision_detection_fcl/test_fcl_collision_detection_panda" TIMEOUT "60" WORKING_DIRECTORY "/server_ws/build/moveit_core/collision_detection_fcl" _BACKTRACE_TRIPLES "/opt/ros/foxy/share/ament_cmake_test/cmake/ament_add_test.cmake;118;add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/foxy/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;59;ament_add_gtest;/server_ws/src/moveit2/moveit_core/collision_detection_fcl/CMakeLists.txt;0;")
